variables:
    GIT_DEPTH: "1"

stages:
    - mil-internal-release_build
    - prepare_mil-internal-release_debs

mil-internal-release_build:
    tags:
        - Runner-Stretch
    stage: mil-internal-release_build
    script:
        - dpkg --add-architecture amd64
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20190909/ stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install --allow-unauthenticated -y build-essential:amd64 devscripts
        - dpkg-buildpackage -us -uc -b -aamd64
        - mv ../*.deb .
        - mv ../*.buildinfo .
        - mv ../*.changes .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb
        - ./*.buildinfo
        - ./*.changes

prepare_mil-internal-release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_mil-internal-release_debs
    only:
      refs:
        - stretch/master
    dependencies:
        - mil-internal-release_build
    when: manual
    script:
        - mkdir -p /cache/stretch/mil-internal-release/
        - cp *.deb /cache/stretch/mil-internal-release/
        - ls /cache/stretch/mil-internal-release/
